### ISSUE TITLE
Prepend dropdown fields

### ISSUE THREAD

**Issue by jwahlin** [Strategy11/formidable-bootstrap#3]
https://formidablepro.com/help-desk/prepend-and-append-option-for-dropdown-field/#comment-170789

**Comment by stephywells** [comment]
I don't remember why we didn't allow this before. I'm not seeing any issues with it, so I went ahead and added it.

**Comment by jwahlin** [comment]
I don't remember why we didn't add this in either. Seemed to work well for me.
